import type {Metadata} from "next";
import "../app/globals.css";
import {Manrope} from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const marope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EquiFit - High Performance Equestrian Gear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marope.variable} bg-color-[#f6f8f6] font-display text-[#121811]`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
